### ISSUE TITLE
Unable to prepare setup for platform sleep_as_android.sensor: Platform not found

### ISSUE THREAD

**Issue by TheRealWaldo** [IATkachenko/HA-SleepAsAndroid#11]
### Integration

**Integration version:**  v1.2.1
**Root topic:** Integration fails configuration checks
### Application settings

**topic:** Can't check (application won't start) but believe it was default
[ ] I can see MQTT messages from application at MQTT-server
## How it works now?
Integration fails to load
## What do you expect?
Integration should load!
## Steps to reproduce
Install the integration
## Debug log
```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 12:00:55 PM (1 occurrences)
Last logged: 12:00:55 PM

Unable to prepare setup for platform sleep_as_android.sensor: Platform not found (cannot import name 'TRIGGER_BASE_SCHEMA' from 'homeassistant.components.device_automation' (/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py)).
```
## Additional information

Just upgraded to core-2021.7.0

**Comment by IATkachenko** [comment]
Thank you for report. Will check at 2021.7.0

**Comment by IATkachenko** [comment]
Should be fixed in v1.2.2.
@TheRealWaldo, could you confirm that all goes well?

**Comment by TheRealWaldo** [comment]
@IATkachenko seems to be working for me now, thanks for the quick response!

**Comment by IATkachenko** [comment]
Welcome!
ps. just for history: v1.2.2 broke compatibility with older version of HA. v1.2.3 fix this too and should work for all versions of HA: older than 2021.7 and newer.

**Comment by TheRealWaldo** [comment]
@IATkachenko got it, and it seems to be working!
