### ISSUE TITLE
No integration showing up

### ISSUE THREAD

**Issue by KeerlITServices** [IATkachenko/HA-SleepAsAndroid#29]
### Home Assistant
**2021.12.4:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[X] Operating System
[ ] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[X] HACS
[ ] manual from release
[ ] manual from git
**Integration version:v1.6.0** 
**Root topic:** 
### Application settings

**topic:**
[X] I can see MQTT messages from application at MQTT-server
## How it works now?
After installing the SAA Integration and restarting HA, the SAA Integration is not available under Settings / Integrations
## What do you expect?
N/A
## Steps to reproduce
1. Install Integration through HACS as described
2. Restart HA
3. Go to Settings / Integrations / Add integration
4. Select / Search Slaap As Android
## Debug log
```
No output generated, despite having added the debug setting to my config.yaml
```

**Comment by IATkachenko** [comment]
@KeerlITServices, hello.
At step 4: `Select / Search Slaap As Android`. Is it misstype and actually you have tried to find "Sleep As Android" (double "e" in the first word)?

Also could you check:
1. that HACS works well and you have `sleep_as_android` folder in `custom_components/`?
2. that you have record like
```
2021-12-20 23:28:34 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sleep_as_android which has not been tested by Home Assistant. 
```
in log while startup.

**Comment by KeerlITServices** [comment]
Hi,

Yes, that was a mistype (slaap is Dutch for sleep)

HACS works fine, other integrations work fine.
Folder is there, the warning does appear too at startup.

JK
________________________________

**Comment by IATkachenko** [comment]
It is very strange... I'll check at 2021.12.4 later.

By the way, have you any warnings/errors while HA starts? May something prevent integrations load?

PS JFYI: I'm running 2021.12.3 now: all goes well.

**Comment by IATkachenko** [comment]
After updating to 2021.12.4 all goes well too.
Will try fresh (docker, I can't run HomeAssistant OS by some reasons) installation.

**Comment by IATkachenko** [comment]
Sorry, could not reproduce at fresh docker 2021.12.4.
![изображение](https://user-images.githubusercontent.com/17473830/147222412-3fe7ee62-bec3-4613-80ab-c45edce89dbb.png)

If `sleep_as_android` is in `custom_components/` (and it is not empty), HA is loading the integration (according to log record) and there is no errors in log, then it should be available in "Add integration" menu.
Have no idea what is going wrong in your case. Try to remove integration from HASC, restart HA, install it again and one more restart. May be something went wrong while installation process...

Will try HomeAssistant OS, but it will not be soon.

**Comment by WhiteNoseThunderPants** [comment]
I know this is an older issue, but I have had similar problems with the integration menu due to browser cache issues.

@IATkachenko & @KeerlITServices

**Comment by IATkachenko** [comment]
@WhiteNoseThunderPants, thank you! 
I'll add this information to WiKi.

@KeerlITServices, is all goes well for you with cleaned browser cache or in "Private window" mode?

**Comment by KeerlITServices** [comment]
> @WhiteNoseThunderPants, thank you! I'll add this information to WiKi.
> 
> @KeerlITServices, is all goes well for you with cleaned browser cache or in "Private window" mode?

Hiya!
Thanks @WhiteNoseThunderPants for reminding me!
I did realise a few days ago, that this might be the case here too - the developer of an other AddOn did have the info in their wiki.
I just forgot to update you all. Sorry for that!

Now it's all there and working :)

**Comment by IATkachenko** [comment]
Nice!
Will keep this issue open till documentation update.
