### ISSUE TITLE
Alarm Name As Part of Trigger

### ISSUE THREAD

**Issue by MikeKMiller** [IATkachenko/HA-SleepAsAndroid#30]
# General information

Include Alarm Name as Part of Trigger Definition

# Usage scenario

I use alarms in SleepAsAndroid for both Wake Up Alarms, as well as various reminders throughout the day. Being able to filter by specific Alarm Names would allow setting automations based on specific alarms.

The MQTT call from SleepAsAndroid includes value2 which usually contains the Alarm Name.

**Comment by IATkachenko** [comment]
I'm not sure that it is a good idea to add various parameter to trigger name (and it is look like we must define all trigger names at stage of integration loading).

Will it be OK if we add additional attribute (`value2` or `name`) to sensor? 
This attribute will have state:
 * equal to value2 if MQTT message contain it;
 * unavailable if there is no value2 in MQTT message.
Then you will be able check this attribute and do different things based on it.

**Comment by MikeKMiller** [comment]
Yes, that would work for what I am hoping to do with it.

**Comment by IATkachenko** [comment]
OK. 
Will add it in next release.

**Comment by IATkachenko** [comment]
Done in dev branch.
Release will be in a few days: will test it at own installation before.

**Comment by MikeKMiller** [comment]
Thank you
