### ISSUE TITLE
Old devices have no delete option

### ISSUE THREAD

**Issue by thomasfinstad** [IATkachenko/HA-SleepAsAndroid#48]
### Home Assistant
**Version:** 2022.11.1
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[x] Linux VM
[ ] Operating System
[ ] Container
[ ] Supervised
[ ] Core
### Integration

**Installation method:**
[x] HACS
[ ] manual from release
[ ] manual from git
**Integration version:** 1.9.2
**Root topic:** nothing? not sure where to check that setting
### Application settings

**topic:** sensor/SleepAsAndroid/%%%device%%%
[x] I can see MQTT messages from application at MQTT-server
## How it works now?
99.9% as expected, everything works great, except I have old devices that I can not delete from HA that have been changed out for other phones etc.
## What do you expect?
The device to be deleteable in the devices screen
## Steps to reproduce
Not sure, but I think

 1. add phone as a sensor
 2. change the device name
 3. old device has no delete button in device list 
## Debug log
```
N/A
```
## Additional information
Thank you for the great quality of life boost this is giving me!

**Comment by IATkachenko** [comment]
@thomasfinstad, thank you for report.

"Delete" button will be useful. 

Will check how to add it.

**Comment by thomasfinstad** [comment]
> For now you may disable device (via corresponding switch) in edit menu at top-right conner of the device screen.

I will keep the old device as disabled for now until there is a way to fully delete it.
I ask that you keep this issue open until there is a way to delete devices, as an indicator to others with the same question.

**Comment by IATkachenko** [comment]
Sure. It should be fixed, but I can't see way to do it.
For now I could not understand what kind of data should be provided by the integration to enable `delete` button.

**Comment by IATkachenko** [comment]
Yes, it is work. 
Release will be ready in few minutes.

**Comment by IATkachenko** [comment]
Fixed in [v1.10.0](https://github.com/IATkachenko/HA-SleepAsAndroid/releases/tag/v1.10.0)
