### ISSUE TITLE
No entity for sleep as android In Home Assistant 

### ISSUE THREAD

**Issue by hdjweb** [IATkachenko/HA-SleepAsAndroid#7]
I have done all your passages in documentation: App Configuration:
![Screenshot_20210402_135146_com urbandroid sleep](https://user-images.githubusercontent.com/48908797/113413298-9e104a80-93ba-11eb-9da7-c0489e7cb257.jpg)
Home assistant Configuration:
![Screenshot_20210402_135348](https://user-images.githubusercontent.com/48908797/113413384-e2034f80-93ba-11eb-9e92-34143579e509.jpg)
I restart but i have not entities why?????
Id i see logs i can se connected client and After disconnected at the Same back issue??

**Comment by hdjweb** [comment]
I peace you Aldo mosquito broker addon please help me.
![Screenshot_20210402_140307](https://user-images.githubusercontent.com/48908797/113414019-4541b180-93bc-11eb-8491-ee78963481c3.jpg)

**Comment by IATkachenko** [comment]
@hdjweb, hello.

Please try to use just `SleepAsAndroid` in Integration settings. 
Integration will search subtopics in it and will create Separate instances for every subtopic.

**Comment by hdjweb** [comment]
Nothing happen, i removed integrativo i restarted home assistant, i added again this in addon configuration:
![Screenshot_20210402_183312](https://user-images.githubusercontent.com/48908797/113434828-f1e25a00-93e1-11eb-8906-ec28a4f6f9b3.jpg)
I restarted home assistant but i have the Same problem
![Screenshot_20210402_183427](https://user-images.githubusercontent.com/48908797/113434908-176f6380-93e2-11eb-87c0-ea9aa716cb42.jpg)

**Comment by IATkachenko** [comment]
OK, lets check HomeAssistant logs.
Could you turn on debug in configuration.yaml and post logs that is related to integration?
```yaml
logger:
  default: warning
  logs:
    custom_components.sleep_as_android: debug
```

Also, could you check via some MQTT browser (like MQTT Explorer for Windows or something like it for any other OS) that the Application is publishing something after the Integration was configured.

**Comment by hdjweb** [comment]
Ok this Is what i find in homeassistant.log about your component
[custom_components.sleep_as_android] Setting up 2e638aebcfbe75dcf0fca7f22463ad84 
[custom_components.sleep_as_android.sensor] Subscribing to root topic 'SleepAsAndroid'
2021-04-02 21:32:37 ERROR (MainThread)
[custom_components.sleep_as_android.sensor] Subscribing to root topic is done!
2021-04-02 21:32:45 ERROR (MainThread)

**Comment by IATkachenko** [comment]
Interesting.
The last message must not be at ERORR level (it should be just DEBUG and fires only if we had sucessfully subscribed to root topic).

By the way: what about messages at the MQTT server? The integration need to catch atleast one message to create device in HomeAssistant. Subscribing works fine, so device should be created (or we catch something in logs).

**Comment by IATkachenko** [comment]
@hdjweb, is any news?

**Comment by hdjweb** [comment]
Yes 8 solved i write in topic SleepAsAndroid/Client1 and all Is good thanks you so much

**Comment by IATkachenko** [comment]
@hdjweb, nice!

Feel free to open new issues if something went wrong. 

Ps. If you suppose that this project is useful, please star it to help other peoples to find it.
