### ISSUE TITLE
Topic text too long

### ISSUE THREAD

**Issue by fortepc** [IATkachenko/HA-SleepAsAndroid#8]
![image](https://user-images.githubusercontent.com/26149601/115067274-ab4f2e00-9ebe-11eb-8167-605482e3ba70.png)
Setting up the integration the topic text is too long, and there is seemingly no way to view the full length of what it's trying to tell me.

**Comment by IATkachenko** [comment]
@fortepc, hello.

Thank you for using this integration and issue report.

Unfortunately I don't know how to use multiline text here. Ways like `\n` `<br/>` is not work.
Full text is:
```
Topic at MQTT-server with Sleep As Android subtopics. All subtopics will be created as independent devices. Must be consistent with application settings.
```

I'll keep this issue open, while I trying to find solution.
